/*
 * Embedded bitmap font for the graphical BDS UI.
 *
 * Glyphs on a 32px-tall grid, 4-bit anti-aliased alpha (16 levels), two
 * pixels packed per byte, row-major.  Metrics are unified so mixed-script
 * text lines up cleanly: every CJK ideograph and fullwidth form shares one
 * uniform 26px advance with the ink centred in the cell, while Latin/ASCII
 * stays proportional (ink width plus a 2px pad).  Covers the full printable
 * ASCII range plus every CJK character used by the UI string table;
 * characters outside the table are rendered as a hollow placeholder box by
 * the drawing code.
 *
 * Copyright (c) 2026, contributors to the canoe ABL tree.
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __SUPER_FB_FONT_H__
#define __SUPER_FB_FONT_H__

#include <Uefi.h>

#define SFB_FONT_CELL_H             32
#define SFB_FONT_MAX_W              32
#define SFB_FONT_MAX_ALPHA          15

typedef struct {
  CHAR16  Ch;        /* Unicode code point */
  UINT32  Offset;    /* byte offset into gSfbFontBitmap */
  UINT8   Width;     /* glyph width in pixels (even) */
  UINT8   Advance;   /* pen advance in pixels (includes side padding) */
} SFB_FONT_GLYPH;

/* Generated by tools/gen_sfb_font/gen_sfb_font.ps1. */
extern CONST UINT8          gSfbFontBitmap[];
extern CONST UINTN          gSfbFontGlyphCount;
extern CONST SFB_FONT_GLYPH gSfbFontGlyphs[];

/*
 * Look up the glyph for Ch.  Returns TRUE and fills Offset/Width/Advance, or
 * FALSE when the character has no glyph.
 */
BOOLEAN
SfbFontGetGlyph (IN CHAR16 Ch,
                 OUT UINT32 *Offset,
                 OUT UINT8  *Width,
                 OUT UINT8  *Advance);


#endif /* __SUPER_FB_FONT_H__ */
